# This file will be included by the Makefile under the project directory.
lib_common_CFLAGS_EXTRA := -m32 -fno-builtin \
			-I$(LIB_COMMON_DIR)


FLOAT_OBJ := $(FLOAT:.a=.o)
FLOAT_SRC := $(LIB_COMMON_DIR)/FLOAT.c


$(FLOAT): $(FLOAT_OBJ)
	ar r $(FLOAT) $(FLOAT_OBJ)

$(FLOAT_OBJ): $(FLOAT_SRC)
	$(call make_command, $(CC), $(lib_common_CFLAGS_EXTRA), ld $@, $(CFLAGS) $(FLOAT_SRC))
# TODO: write a rule for generating $(FLOAT_OBJ)

